### ISSUE TITLE
Possible to build in a JACK client?

### ISSUE THREAD

**Issue by samuelthewhale** [gethiox/HIDI#3]
Would it be possible to allow the program to connect to a JACK server so that the MIDI signals can be piped to a VST or LV2?

**Comment by gethiox** [comment]
It is possible for Linux users, I have local changes that implements that by using rtmidi interface. However, due to my current health shape I'm unable to deliver required code updates. It is really hard to tell when my situation will get better.

**Comment by gethiox** [comment]
The best I can do for now is ALSA integration, it should work well with JACK when `seq` midi driver is selected.  
I tried to implement JACK via [gomidi](https://github.com/gomidi/midi) but failed to make it work, [go-jack](https://github.com/xthexder/go-jack) might work but I faced the issue of running application under root instead of user where JACK server is unavailable.
I'll release HIDI 1.0 soon:tm: and we will see if this is sufficient.

**Comment by gethiox** [comment]
v1.0.0 has been released which introduces ALSA backend integration, please let me know if that resolves your issue, if not I'll leave it open and try to deliver JACK support another time.
To run application in standalone mode use `sudo ./HIDI-linux-amd64 -grab -standalone -virtual`

**Comment by masaeedu** [comment]
@gethiox Glad to see you're feeling better, and thank you for all your work on this project.

**Comment by gethiox** [comment]
From my research JACK integration would be difficult to achieve as JACK client requires to run under user privileges, not root. Root is required to have direct access to input devices and run OpenRGB properly.
Closing this issue as ALSA integration should be sufficient for now.
